### ISSUE TITLE
Support non string IDs

### ISSUE THREAD

**Issue by CAMOBAP** [relaton/jekyll-theme-relaton-data-index#2]
Origin and proposed design: https://github.com/relaton/relaton-data-w3c/pull/11#issuecomment-1705613032

**Comment by andrew2net** [comment]
@CAMOBAP please keep in mind:

1. If some part is omitted then a delimiter should also be omitted.
2. In some cases we don't have any delimiter at all between specific parts.

It may be tricky because in some cases the first part is omitted, in some cases last or middle part is omitted. Maybe we should use the setting like:
```yaml
jekyll-index:
  reference:
    - part: :type
      delim_after: '-'
    - part: :code
    - delim_before: '-'
      part: :date
```
For W3C's index1.yaml only `code` is mandatadory. Other parts can be omitted. For other repos we need to use other settings.
